#!/usr/bin/env bash

# Backup files
mv ~/.bashrc ~/.bashrc.old

files=( ".bashrc" ".bash_prompt" ".gitconfig" ".gitignore" ".tmux.conf" )

if hash wget 2>/dev/null; then
    for file in "${files[@]}"
    do
        wget -O ~/$file https://raw.githubusercontent.com/tim-antkowiak/dotfiles/master/$file
    done
else if hash curl 2>/dev/null; then
    for file in "${files[@]}"
    do
        curl https://raw.githubusercontent.com/tim-antkowiak/dotfiles/master/$file --output ~/$file
    done
else
    echo "wget and curl not available"
fi

. ~/.bashrc
